// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_0NCL4DoMV44RJgp0Jkq7b8ZTVe9e_8c',
    appId: '1:851706409758:web:9703dadff78a5290c80f0f',
    messagingSenderId: '851706409758',
    projectId: 'santos-1b6f6',
    authDomain: 'santos-1b6f6.firebaseapp.com',
    storageBucket: 'santos-1b6f6.appspot.com',
    measurementId: 'G-XXBXKGLFG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGzkp7bMQRw393Ry9gocJNkB6ig4DD_18',
    appId: '1:851706409758:android:9624a5fc68beb66dc80f0f',
    messagingSenderId: '851706409758',
    projectId: 'santos-1b6f6',
    storageBucket: 'santos-1b6f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6hKy--llaiZ5p9ZNH1gCOuvSv5Gjw2iY',
    appId: '1:851706409758:ios:916ba1166193ebbbc80f0f',
    messagingSenderId: '851706409758',
    projectId: 'santos-1b6f6',
    storageBucket: 'santos-1b6f6.appspot.com',
    iosClientId: '851706409758-qak4t60rj4vkbokggh89uci9v3u9dbmp.apps.googleusercontent.com',
    iosBundleId: 'pro.joaosousa.queueManagementSystem',
  );
}
